name: Process PRs

on:
  push:
    branches: [ 'gh-readonly-queue/main/**' ]
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-ci:
    uses: relaycorp/shared-workflows/.github/workflows/pr-ci.yml@main
